name: Configure AWS Credentials
uses: aws-actions/configure-aws-credentials@v4
with:
   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   aws-region: ap-south-1

jobs:
  AWS_Access:
    runs_on: ubuntu-latest

    steps:
      - name: Access AWS S3
        run: aws s3 ls

      - name: Access AWS EC2
        run: aws ec2 describe-instances

      - name: Access AWS EKS
        run: aws eks list-clusters
