name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  IMAGE_NAME: springboot-app
  AWS_REGION: us-east-1
  EKS_CLUSTER: my-eks-cluster

jobs:

# BUILD + SECURITY
  build:

    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ github.sha }}

    permissions:
      contents: read

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    # JAVA
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    # BUILD
    - name: Build
      run: mvn clean package

    # UNIT TEST    
    - name: Run Unit Tests
      run: mvn test

    # SONARQUBE (SAST)
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=myapp \
        -Dsonar.host.url=http://SONAR_SERVER:9000 \
        -Dsonar.login=$SONAR_TOKEN

    # OWASP Dependency Check
    - name: OWASP Dependency Check
      run: |
        mvn org.owasp:dependency-check-maven:check

    # SECRET SCAN
    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2

    # LOGIN DOCKER
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # BUILD IMAGE
    - name: Build Docker Image
      run: |
        docker build \
        -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    # TRIVY
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    # PUSH IMAGE
    - name: Push Docker Image
      run: |
        docker push \
        ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

# DEPLOY
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: production                               //Workflow pauses until approval done

    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # AWS LOGIN USING OIDC
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    # verify authentication
    - name: Verify AWS Login
      run: |
          aws sts get-caller-identity

   
    # CONFIGURE EKS
    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $EKS_CLUSTER

    # check nodes
    - name: Check Nodes
      run: |
        kubectl get nodes
        
    # DEPLOY
    - name: Update Deployment
      run: |
        kubectl set image deployment/myapp \
        myapp=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image-tag }}

    # VERIFY
    - name: Verify Rollout
      run: |
        kubectl rollout status deployment/myapp

    - name: Verify Pods
      run: |
        kubectl get pods

    - name: Verify Services
      run: |
        kubectl get svc
