name: Node.js CI
on:
  pull_requests:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build_node:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version:  "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

      - name: Build App
        run: npm run build
