//At workflow level 
name: Env Example

on:
  workflow_dispatch:

env:
  APP_NAME: myapp
  REGION: us-east-1

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print variables
        run: |
          echo "App: $APP_NAME"
          echo "Region: $REGION"


//At Job Level
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "17"

    steps:
      - run: echo "Java Version: $JAVA_VERSION"


//At STEP Level
steps:
  - name: Print message
    env:
      MESSAGE: Hello DevOps
    run: echo "$MESSAGE"
