name: AWS Access

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  aws_access:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify AWS Login
        run: aws sts get-caller-identity

      - name: List S3 Buckets
        run: aws s3 ls

      - name: List EC2 Instances
        run: aws ec2 describe-instances

      - name: List EKS Clusters
        run: aws eks list-clusters
