name: Sample Triggers/Events

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 2 * * *"

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "Testing from Triggers & Events"
